---
- name: Add the go cd repo
  become: yes
  yum_repository:
    name: gocd
    description: adding gocd repo
    baseurl: https://download.gocd.io
    enabled: yes
    gpgkey: https://download.gocd.io/GOCD-GPG-KEY.asc
    gpgcheck: yes

- include_role:
    name: java-jdk