---
- name: Download Oracle JDK rpm
  become: yes
  get_url:
    url: "{{oracle_jdk_rpm_url}}"
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"
    dest: "{{destination}}"
    checksum: "{{checksum}}"

- name: Install JDK
  become: yes
  yum:
    name: "{{destination}}"